version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    insecure-external-code-execution: allow
    schedule:
      interval: "monthly"
    labels:
      - "Maintenance"
      - "Dependencies"
    ignore:
      # Exclude main project dependencies and optional dependencies (like reader)
      - dependency-name: "ansys-api-fluent"
      - dependency-name: "ansys-platform-instancemanagement"
      - dependency-name: "ansys-tools-filetransfer"
      - dependency-name: "ansys-units"
      - dependency-name: "defusedxml"
      - dependency-name: "deprecated"
      - dependency-name: "docker"
      - dependency-name: "grpcio"
      - dependency-name: "grpcio-health-checking"
      - dependency-name: "grpcio-status"
      - dependency-name: "nltk"
      - dependency-name: "numpy"
      - dependency-name: "pandas"
      - dependency-name: "pyansys-tools-report"
      - dependency-name: "pyyaml"
      - dependency-name: "h5py"
      - dependency-name: "tensorflow"
      - dependency-name: "matplotlib"
      - dependency-name: "plotly"
      - dependency-name: "scikit-learn"
      - dependency-name: "seaborn"
      - dependency-name: "xgboost"
      - dependency-name: "imageio"
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "Maintenance"
    groups:
      actions:
        patterns:
          - "*"
